### ISSUE TITLE
jitter do not work properly

### ISSUE THREAD

**Issue by stephexcel2004** [VizWizard/BoxPlotR.shiny#24]
Assuming there 5 same boxplots created in a graph, the data point of the first boxplot with jitter option will still have over-plotting problem. It can be seen that the over plotting problems decrease from one boxplot to another from left to right.

**Comment by VizWizard** [comment]
Thank you very much for submitting this issue. The effect can be seen with the sample data set. We will look into this.

**Comment by MichaelaEBI** [comment]
jitter does now work properly.
