### ISSUE TITLE
Website seems to be broken

### ISSUE THREAD

**Issue by oneEyedSunday** [VizWizard/BoxPlotR.shiny#35]
Hello @VizWizard thanks for this beautiful software.
I am trying to add new datapoints to my thesis and tried to visualise via the [website](http://shiny.chemgrid.org/boxplotr/) but whatever I do, I cannot seem to get any visualisations.

I have tried using the "load sample data" option, with default settings to no avail.
I used the website to obtain visualisations as late as third quarter of last year.
I've also tried using the exact same datasets I used last year, but also to no avail.

I've checked through the commit logs and notice some new commits some 18 days ago.

I've done some poking around on the website and see no console errors or even API calls being made.

I would try to follow the instructions on running the project locally, and try to point to earlier commits to see if that solves my issue. Thank you.

**Comment by MichaelaEBI** [comment]
Hello @oneEyedSunday. Thank you for your message. Are there any error messages? I have tried the website just now and the sample datasets work fine for me. Entering data manually also works for me. Could you attach a screenshot or send one by email?

**Comment by oneEyedSunday** [comment]
I'd attach screenshots here.

I get no errors whatsoever in the console. I also notice no API calls get made.

<img width="1440" alt="Screenshot 2021-02-05 at 11 35 03" src="https://user-images.githubusercontent.com/29808443/107023062-6b751780-67a6-11eb-8915-b614fbabaf61.png">
<img width="1440" alt="Screenshot 2021-02-05 at 11 34 59" src="https://user-images.githubusercontent.com/29808443/107023084-6fa13500-67a6-11eb-88f2-c039f8ee695b.png">
<img width="323" alt="Screenshot 2021-02-05 at 11 34 00" src="https://user-images.githubusercontent.com/29808443/107023089-70d26200-67a6-11eb-8556-fbfb9475ebd3.png">
<img width="1440" alt="Screenshot 2021-02-05 at 11 33 56" src="https://user-images.githubusercontent.com/29808443/107023092-716af880-67a6-11eb-9dd7-05ad83115f24.png">
<img width="1440" alt="Screenshot 2021-02-05 at 11 33 34" src="https://user-images.githubusercontent.com/29808443/107023096-729c2580-67a6-11eb-8a79-16f99059c1ec.png">
<img width="1440" alt="Screenshot 2021-02-05 at 11 33 31" src="https://user-images.githubusercontent.com/29808443/107023099-73cd5280-67a6-11eb-9f42-7b724b775266.png">

These screenshots show the data selection, the blank visualisation screen , my console tab and network tab.

**Comment by oneEyedSunday** [comment]
Hello @VizWizard  screenshots uploaded here. Perhaps Im missing the visualisation trigger.

**Comment by MichaelaEBI** [comment]
Hi @oneEyedSunday - the app does not even load the data. The data (or at least some of it) should show on the 'Data upload' tab. Have you tried a different browser? Have you used R before? I am happy to help you getting it to run locally.

**Comment by oneEyedSunday** [comment]
I've not used R before, but I've gotten R and R studio installed using [this](https://medium.com/@GalarnykMichael/install-r-and-rstudio-on-mac-e911606ce4f4)

Ive had to install via `install.packages("shiny", method="wget")`

Currently installing the packing listed in the [README](https://github.com/VizWizard/BoxPlotR.shiny/blob/master/README.md)

**Comment by oneEyedSunday** [comment]
I would really love to not have to run this locally, the problem (not loading the data) persists in Chrome (the screenshots were taken from Safari)

**Comment by oneEyedSunday** [comment]
Now, im getting this
```
ERROR: dependencies 'httpuv', 'mime', 'jsonlite', 'digest', 'htmltools', 'sourcetools', 'later', 'promises', 'rlang', 'fastmap', 'commonmark', 'glue', 'bslib', 'cachem', 'ellipsis', 'lifecycle' are not available for package 'shiny'
* removing '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/shiny'
```

**Comment by oneEyedSunday** [comment]
Tried [this](https://github.com/rstudio/shiny/issues/215#issuecomment-28912752) yet get a similar error

**Comment by oneEyedSunday** [comment]
This seems to be the overall culprit
```
> install.packages(c("'httpuv'", "'mime'", "'jsonlite'", "'digest'", "'htmltools'", "'sourcetools'", "'later'", "'promises'", "'rlang'", "'fastmap'", "'commonmark'", "'glue'", "'bslib'", "'cachem'", "'ellipsis'", "'lifecycle'"))
Warning in install.packages :
  packages ''httpuv'', ''mime'', ''jsonlite'', ''digest'', ''htmltools'', ''sourcetools'', ''later'', ''promises'', ''rlang'', ''fastmap'', ''commonmark'', ''glue'', ''bslib'', ''cachem'', ''ellipsis'', ''lifecycle'' are not available (for R version 3.2.1)
```

Upgrading to 3.4 or 3.5...

**Comment by oneEyedSunday** [comment]
Now facing this
```
> devtools::install_github("rstudio/shiny-incubator")
Downloading GitHub repo rstudio/shiny-incubator@HEAD
tar: Failed to set default locale
tar: Failed to set default locale
Error: Failed to install 'shinyIncubator' from GitHub:
  missing value where TRUE/FALSE needed
```

**Comment by oneEyedSunday** [comment]
ok @VizWizard  I can get it to run locally at 54d071c238c5a735a59fbfa87e40556854fe268e and master
I get this error when I try to switch to "paste data"

```
Downloading https://github.com/VizWizard/BoxPlotR.shiny/archive/master.tar.gz

Listening on http://127.0.0.1:5975
[1] 100
NULL
Warning: Error in if: argument is of length zero
Warning: Error in if: missing value where TRUE/FALSE needed
Error in if (has_color()) { : missing value where TRUE/FALSE needed
```

**Comment by MichaelaEBI** [comment]
This error should disappear as soon as you type or paste (valid) data into the text box.

**Comment by oneEyedSunday** [comment]
Problem is the application crashes and the local windows closes

**Comment by oneEyedSunday** [comment]
Hello @VizWizard  the website now works for me.
Tears of joy ;)


Seems to be intermittent. Its disconnected, and now even with a page refresh, it doesn't come back up

**Comment by MichaelaEBI** [comment]
Hm, very strange. The website still works perfectly for me.

**Comment by oneEyedSunday** [comment]
Im getting way better results behind a VPN

**Comment by oneEyedSunday** [comment]
I'm closing this now, can you replicate this issue?

https://github.com/VizWizard/BoxPlotR.shiny/issues/35#issuecomment-773994598

https://github.com/VizWizard/BoxPlotR.shiny/issues/35#issuecomment-773996460

May need some looking into.
